# Generated by Django 3.2.6 on 2021-08-19 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bairros',
            fields=[
                ('id_bairro', models.IntegerField(primary_key=True, serialize=False)),
                ('id_cidade', models.IntegerField(blank=True, null=True)),
                ('nome', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'bairros',
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('idendereco', models.IntegerField(db_column='idEndereco', primary_key=True, serialize=False)),
                ('logradouro', models.CharField(blank=True, db_column='Logradouro', max_length=45, null=True)),
                ('numero', models.IntegerField(blank=True, db_column='Numero', null=True)),
                ('complemento', models.CharField(blank=True, db_column='Complemento', max_length=45, null=True)),
                ('bairro', models.CharField(blank=True, db_column='Bairro', max_length=45, null=True)),
                ('cep', models.CharField(blank=True, db_column='CEP', max_length=10, null=True)),
            ],
            options={
                'db_table': 'endereco',
            },
        ),
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('idfilial', models.AutoField(db_column='idFilial', primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, db_column='Nome', max_length=45, null=True)),
                ('idendereco', models.IntegerField(blank=True, db_column='idEndereco', null=True)),
            ],
            options={
                'db_table': 'filial',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('idperfil', models.AutoField(db_column='IdPerfil', primary_key=True, serialize=False)),
                ('atribuicao', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'perfil',
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('idpessoa', models.IntegerField(db_column='idPessoa', primary_key=True, serialize=False)),
                ('cpf', models.CharField(blank=True, db_column='CPF', max_length=11, null=True)),
                ('nome', models.CharField(blank=True, db_column='Nome', max_length=45, null=True)),
                ('cnh', models.CharField(blank=True, db_column='CNH', max_length=10, null=True)),
                ('categoria', models.CharField(blank=True, db_column='CATEGORIA', max_length=2, null=True)),
                ('rntrc', models.IntegerField(blank=True, db_column='RNTRC', null=True)),
                ('e_mail', models.CharField(blank=True, db_column='e-mail', max_length=45, null=True)),
                ('idusuario', models.IntegerField(blank=True, db_column='idUsuario', null=True)),
                ('idfilial', models.IntegerField(blank=True, db_column='idFilial', null=True)),
                ('idendereco', models.IntegerField(blank=True, db_column='idEndereco', null=True)),
            ],
            options={
                'db_table': 'pessoa',
            },
        ),
        migrations.CreateModel(
            name='Uf',
            fields=[
                ('id_uf', models.IntegerField(primary_key=True, serialize=False)),
                ('sigla', models.CharField(blank=True, max_length=3, null=True)),
                ('estado', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'UF',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.AutoField(db_column='idUsuario', primary_key=True, serialize=False)),
                ('login', models.CharField(blank=True, max_length=45, null=True)),
                ('senha', models.CharField(blank=True, max_length=45, null=True)),
                ('idperfil', models.CharField(blank=True, db_column='idPerfil', max_length=45, null=True)),
                ('status', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Cidades',
            fields=[
                ('id_cidade', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=200, null=True)),
                ('id_uf', models.ForeignKey(blank=True, db_column='id_uf', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cadastro.uf')),
            ],
            options={
                'db_table': 'cidades',
            },
        ),
    ]
